echo ""
echo "                                   ___"
echo "                               ,-""   `."
echo "                             ,'  _   e )`-._"
echo "                            /  ,' `-._<.===-'"
echo "                           /  /"
echo "                          /  ;"
echo "              _          /   ;"
echo " (`._    _.-"" ""--..__,'    |"
echo " <_  `-""                     \"
echo "  <`-                          :"
echo "   (__   <__.                  ;"
echo "     `-.   '-.__.      _.'    /"
echo "        \      `-.__,-'    _,'"
echo "         `._    ,    /__,-'"
echo "            ""._\__,'< <____"
echo "                 | |  `----.`."
echo "                 | |        \ `."
echo "                 ; |___      \-``"
echo "                 \   --<"
echo "                  `.`.<"
echo "                    `-'"
echo ""
echo "hahaha you are a silly goose. lolol"
